# Generated by Django 5.2.7 on 2025-10-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('military', '0003_alter_militarybase_options_alter_militarybase_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pistola', 'Pistola'), ('Carabina', 'Carabina'), ('Fuzil', 'Fuzil')], max_length=50, verbose_name='Tipo')),
                ('model_type', models.CharField(choices=[('PT100', 'PT100'), ('PT840', 'PT840'), ('IA2', 'IA2'), ('SMT40', 'SMT40')], default='PT100', max_length=50, verbose_name='Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('caliber', models.CharField(choices=[('40mm', '40mm'), ('5.56mm', '5.56mm'), ('7.62mm', '7.62mm')], max_length=50, verbose_name='Calibre')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('status', models.CharField(choices=[('Cautela Provisória', 'Cautela Provisória'), ('Cautela Permanente', 'Cautela Permanente'), ('Reserva', 'Reserva')], max_length=50, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military.militarybase', verbose_name='Portador')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ['type'],
            },
        ),
    ]
