# Generated by Django 5.2.7 on 2025-10-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarybase',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='id_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='military_rank',
            field=models.CharField(max_length=50, verbose_name='Posto/Graduação'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='war_name',
            field=models.CharField(max_length=100, verbose_name='Nome de guerra'),
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='year_entry',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Barra'),
        ),
    ]
