# Generated by Django 5.2.7 on 2025-10-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0002_alter_militarybase_address_alter_militarybase_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militarybase',
            options={'ordering': ['name'], 'verbose_name': 'Militar', 'verbose_name_plural': 'Militares'},
        ),
        migrations.AlterField(
            model_name='militarybase',
            name='cpf',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF'),
        ),
    ]
